### ISSUE TITLE
Access to the Stage Server - SSH Permission denied 

### ISSUE THREAD

**Issue by ArtuGit** [docksal/ci-agent#4]
I want to run a remote script on my Stage server from the Bitbucket Docker Machine.

1. I have an Public Key in Bitbucket Pipeline settings.
2. I added this key to the Stage Server `authorized_keys ` file.
3. I created a Pipeline Environment Variable CI_SSH_KEY wich contains the value of this key.
4. I have the pipeline.
```
image: docksal/bitbucket-pipelines-agent

pipelines:
  custom: # Pipelines that are triggered manually
    test:
      - step:
          script:
            - ssh user@X.XX.XX.XX echo 'Run Test Pipeline'
```

I have such error:
```
 ssh user@X.XX.XX.XX echo 'Run Test Pipeline'
Load key "/opt/atlassian/pipelines/agent/data/id_rsa": Permission denied
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).

```

What is wrong?
