### ISSUE TITLE
DOCKSAL_HOST_SSH_PORT error when cloning repo

### ISSUE THREAD

**Issue by paulsheldrake** [docksal/ci-agent#54]
On the `edge-php` version I'm now getting this error
```
Cloning into '.'...
/home/agent/.ssh/config line 16: Bad port 'DOCKSAL_HOST_SSH_PORT'.
fatal: Could not read from remote repository.
```

reverting to stable version `php` has fixed the issue.

**Comment by lmakarov** [comment]
@paulsheldrake can you share your build config (to the point, where this error happens)?

**Comment by paulsheldrake** [comment]
config.yml
```
jobs:
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:edge-php
    environment:
       BASH_ENV: /home/agent/.bashrc  # Tell CircleCI where to read the shared build environment variables from
    steps:
      - checkout
```
CircleCi step output
```
Cloning into '.'...
/home/agent/.ssh/config line 16: Bad port 'DOCKSAL_HOST_SSH_PORT'.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```

**Comment by lmakarov** [comment]
`source build-env` has to be the very first step in the build. This initializes all variables and configures the agent environment.

See https://github.com/docksal/ci-agent#circleci

```yaml
version: 2

jobs:
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:php
    steps:
      - run:
          name: Configure agent environment
          command: echo 'source build-env' >> $BASH_ENV
      - checkout
      ...
```

`echo 'source build-env' >> $BASH_ENV` ensures `source build-env` happens at every step.

**Comment by paulsheldrake** [comment]
Thanks for getting back to me.

I've updated the config to 

```
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:edge-php
    steps:
      - run:
          name: Configure agent environment
          command: echo 'source build-env' >> $BASH_ENV
      - checkout
```

and switch the  image back to edge and it's failing on the same issue as before
